name: $(Date:yy).$(Date:MM).$(Date:dd)$(Rev:rr)

trigger: none

pool:
  name: 'VSTS Release 01'
  
resources:
  pipelines:
  - pipeline: development # Name of the pipeline resource.
    source: 'TransactionsDisputePortal Development CI' # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run pipeline when any run of completes

  repositories:
  - repository: Templates
    type: git
    name: da/pipelinetemplates

#=========================================================================
# VARIABLES 
#=========================================================================

variables:

  Database: 'TransactionsDisputePortal'
  ArtifactsLocation: 'development\drop'  
  SQLCreateDB: 'CreateDatabase.sql'
  SQLScriptPRE: 'ConfigDatabasePRE.sql'
  SQLMigration: 'Migration.sql'
  SQLScriptPOST: 'ConfigDatabasePOST.sql'
    
#=========================================================================
# DEPLOY STAGE
#=========================================================================
stages:
- stage: Deploy_Database
#=========================================================================
# Job Template Deploy Development 
#=========================================================================
  jobs:
  - template: Deploy/Deploy_Database_SQLServer.yml@Templates
    parameters:
        Database: $(Database)
        Environment: ''
        ResourceName: ''
        Tags: ''
        ArtifactsLocation: $(ArtifactsLocation)  
        SQLCreateDB: $(SQLCreateDB)  
        SQLScriptPRE: $(SQLScriptPRE)  
        SQLMigration: $(SQLMigration)  
        SQLScriptPOST: $(SQLScriptPOST)  