name: $(Date:yy).$(Date:MM).$(Date:dd)$(Rev:rr)

trigger: none

pool:
  name: 'VSTS Release 01'

resources:
  repositories:
  - repository: Templates
    type: git
    name: da/pipelinetemplates

#=========================================================================
# VARIABLES 
#=========================================================================

variables:

- group: Deployment Variables
- group: lib-config-transactionsdisputeportal

- name: ApplicationName
  value: 'transactionsdisputeportalredis' # Must be lowercase
- name: AppNamespace
  value: 'transactionsdisputeportal' # Must be lowercase
- name: Group
  value: 'TransactionsDisputePortal'
- name: OpenShiftEnvironment
  value: 'dev'
- name: Labels
  value: ',team=$(System.TeamProject)'
- name: Team
  value: $(System.TeamProject)
- name: CPURequest
  value: 100m
- name: CPULimit
  value: 200m
- name: MemoryRequest
  value: 50Mi
- name: MemoryLimit
  value: 50Mi

#=========================================================================
# DEPLOY Redis
#=========================================================================
stages:
- stage: Deploy_Redis
#=========================================================================
# Job Template Deploy Development 
#=========================================================================
  jobs:
  - template: Deploy/Deploy_Redis.yml@Templates
    parameters:
        Team: $(Team)
        Environment: 'OpenShift Development'
        OpenShiftEnvironment: $(OpenShiftEnvironment)  
        AppNamespace: $(AppNamespace) 
        ApplicationName: $(ApplicationName)
        Group: $(Group)
        RedisPassword: $(lib-RedisPassword)
        CPULimit: $(CPULimit)
        CPURequest: $(CPURequest)
        MemoryRequest: $(MemoryRequest)
        MemoryLimit: $(MemoryLimit)