name: $(Date:yy).$(Date:MM).$(Date:dd)$(Rev:rr)
trigger:
  branches:
    include:
    - development
  paths:
    exclude:
    - Solution Items/**/*

pool:
  name: 'VSTS Build 01'

resources:
  repositories:
  - repository: Templates
    type: git
    name: da/pipelinetemplates

#=========================================================================
# Variables
#=========================================================================

variables:
- group: 'Deployment Variables'
- group: lib-config-transactionsdisputeportal

- name: ApplicationName
  value: 'transactionsdisputeportal' # Must be lowercase
- name: AppNamespace
  value: 'transactionsdisputeportal' # Must be lowercase
- name: solution
  value: '**/*.sln'
- name: 'intent-solution'
  value: '$(Build.SourcesDirectory)\intent\TransactionsDisputePortal.isln'
- name: 'intent-application-id'
  value: 'b131d440-d48c-4865-bb20-ce273637481f'
- name: 'warning-logging-command'
  value: '##vso[task.logissue type=warning;]{@m} {@x}\n'
- name: 'error-logging-command'
  value: '##vso[task.logissue type=error;]{@m} {@x}\n'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'debug'
- name: ProjectFolder
  value: 'TransactionsDisputePortal.Infrastructure'
- name: StartUpProjectFolder
  value: 'TransactionsDisputePortal.Api'
- name: SQLExpress
  value: False
- name: OpenShiftEnvironment
  value: 'dev'  
- name: Environment
  value: 'Development'     

stages:

#=========================================================================
# Build
#=========================================================================

- stage: Build
  displayName: Build

#=========================================================================
# Job Template CI Build / Intent
#=========================================================================
  jobs:
  - template: CI/CI_Build.yml@Templates
    parameters:
        buildConfiguration: $(BuildConfiguration)
        VSProject: $(ProjectFolder)
        VSStartUpProject: $(StartUpProjectFolder)
        Migrations: true

  - template: CI/CI_Intent.yml@Templates
    parameters:
        intentusername: $(intentusername)
        intentpassword: $(intentpassword)
        intent-solution: $(intent-solution)   
        intent-application-id: $(intent-application-id)   

#=========================================================================
# Test
#=========================================================================
- stage: Test
  displayName: Test & Anaylse

#=========================================================================
# Job Template Unit Tests 
#=========================================================================
  jobs:
  - template: CI/CI_Test.yml@templates
    parameters:
        ApplicationName: $(ApplicationName)
        BuildConfiguration: $(BuildConfiguration)
        solution: $(solution)        
        SonarCloud: false

#=========================================================================
# Publish 
#=========================================================================
- stage: Publish
  displayName: Publish
  dependsOn: 
    - Build
    - Test
#=========================================================================
# Job Template Publish
#=========================================================================
  jobs:
  - template: CI/CI_Publish.yml@templates
    
#=========================================================================
# SQL Express OpenShift
#=========================================================================
- stage: SQLExpress
  displayName: SQL Express Migrations Scripts
  dependsOn: 
    - Publish
  condition: and(
                not(canceled()), eq(variables['SQLExpress'], 'true'), succeeded()
                ) 
#=========================================================================
# Job Template Development SQL Scripts 
#=========================================================================
  jobs:
  - template: Copy/Copy_SQLExpress_Artifacts.yml@templates
    parameters:
        OpenShiftEnvironment: $(OpenShiftEnvironment)
        AppNamespace: $(AppNamespace)
        ApplicationName: $(ApplicationName)
      
      