name: $(Date:yy).$(Date:MM).$(Date:dd)$(Rev:rr)
trigger:
  branches:
    include:
    - main
    - hotfix
  paths:
    exclude:
    - Solution Items/**/*

pool:
  name: 'VSTS Build 01'

resources:
  repositories:
  - repository: Templates
    type: git
    name: da/pipelinetemplates

#=========================================================================
# VARIABLES 
#=========================================================================

variables:

- group: 'Deployment Variables'
- group: lib-config-transactionsdisputeportal

- name: ApplicationName
  value: 'transactionsdisputeportal' # Must be lowercase
- name: AppNamespace
  value: 'transactionsdisputeportal' # Must be lowercase
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: BuildConfiguration
  value: 'Release'
- name: ProjectFolder
  value: 'TransactionsDisputePortal.Infrastructure'
- name: StartUpProjectFolder
  value: 'TransactionsDisputePortal.Api'
- name: SQLExpress
  value: False

stages:

#=========================================================================
# Build
#=========================================================================
- stage: Build
  displayName: Build
  dependsOn:
#=========================================================================
# Job Template CI Build
#=========================================================================
  jobs:

  - template: CI/CI_Build.yml@Templates
  
    parameters:
        buildConfiguration: $(BuildConfiguration)
        VSProject: $(ProjectFolder)
        VSStartUpProject: $(StartUpProjectFolder)
        Migrations: true

#=========================================================================
# Test
#=========================================================================
- stage: Test
  displayName: Test 
  jobs:

#=========================================================================
# Job Template Unit Tests 
#=========================================================================

  - template: CI/CI_Test.yml@templates
    parameters:
        ApplicationName: $(ApplicationName)
        BuildConfiguration: $(BuildConfiguration)
        solution: $(solution)        
        SonarCloud: false

#=========================================================================
# Publish 
#=========================================================================
- stage: Publish
  displayName: Publish
  dependsOn: Build
#=========================================================================
# Job Template Publish
#=========================================================================
  jobs:
  - template: CI/CI_Publish.yml@Templates

#=========================================================================
# SQL Express Scripts - Optional 
#=========================================================================
- stage: OpenShift_SQLExpress
  displayName: Copy SQL Express Database Scripts
  dependsOn: Publish
  condition: and(
                not(canceled()), eq(variables['SQLExpress'], 'true'), succeeded()
                ) 
#=========================================================================
# Job Template Development SQL Scripts 
#=========================================================================
  jobs:
  - template: Copy/Copy_SQLExpress_Artifacts.yml@Templates
  
    parameters:
        OpenShiftEnvironment: 'tst'
        AppNamespace: $(AppNamespace)
        ApplicationName: $(ApplicationName)

  - template: Copy/Copy_SQLExpress_Artifacts.yml@Templates
  
    parameters:
        OpenShiftEnvironment: 'prd'
        AppNamespace: $(AppNamespace)
        ApplicationName: $(ApplicationName)
        OpenshiftService: 'OpenShift-Production'
        Cluster: 'ocp3'

  - template: Copy/Copy_SQLExpress_Artifacts.yml@Templates
  
    parameters:
        OpenShiftEnvironment: 'prd'
        AppNamespace: $(AppNamespace)
        ApplicationName: $(ApplicationName)
        OpenshiftService: 'OpenShift-Production-DR'
        Cluster: 'ocp4'