name: ${{ parameters.Workload_Type }}-$(Date:yy).$(Date:MM).$(Date:dd)$(Rev:rr)

trigger: none

pool:
  name: 'VSTS Build 01'

resources:
  repositories:
  - repository: Templates
    type: git
    name: da/pipelinetemplates

#=========================================================================
# PARAMETERS 
#=========================================================================
parameters:

- name: Workload_Type
  default: api
  values:
  - api
  - scheduler
  - integration

#=========================================================================
# VARIABLES
#=========================================================================

variables:

- group: Deployment Variables
- group: lib-config-transactionsdisputeportal

- name: ApplicationName
  value: 'transactionsdisputeportal' # Must be lowercase
- name: AppNamespace
  value: 'transactionsdisputeportal' # Must be lowercase
- name: Group
  value: 'TransactionsDisputePortal'
- name: ImageName
  value: 'main-transactionsdisputeportal'
- name: buildConfiguration
  value: 'Release'
- name: ProjectFolder
  value: 'TransactionsDisputePortal.Api'
- name: Labels
  value: ',team=$(System.TeamProject)'
- name: Team
  value: '$(System.TeamProject)'

stages:

#=========================================================================
# PREPARE Stage
#=========================================================================
- stage: Prepare
  condition: succeededOrFailed()
    
  jobs:
    - template: Prepare/gitversion_prepare.yml@Templates
      parameters:
        environment: Production
        GitVersionFile: ${{ parameters.Workload_Type }}-GitVersion.yml

#=========================================================================
# BUILD STAGE
#=========================================================================
- stage: Build_Image
  dependsOn: Prepare
  jobs:
  - template: Build/Build_Image.yml@Templates
    parameters:
        ImageName: $(ImageName)                   
        Workload_Type: ${{ parameters.Workload_Type }}
        AppNamespace: $(AppNamespace)
        buildConfiguration: $(buildConfiguration)
        ArtifactsLocation: $(ArtifactsLocation)
        ArtifactsAccessToken: $(ArtifactsAccessToken)
        ProjectFolder: $(ProjectFolder)

#=========================================================================
# DEPLOY TEST STAGE
#=========================================================================

- stage: Deploy_Test
  displayName: Deploy Test  
  dependsOn: Build_Image

#=========================================================================
# Job Template Deploy Test 
#=========================================================================
  variables:
    
  - ${{ if eq(parameters.Workload_Type, 'api') }}:
    - name: CPURequest
      value: 40m
    - name: CPULimit
      value: 120m
    - name: MemoryRequest
      value: 100Mi
    - name: MemoryLimit
      value: 400Mi
    - name: Replicas
      value: 2
  
  - ${{ if eq(parameters.Workload_Type, 'scheduler') }}:
    - name: CPURequest
      value: 40m
    - name: CPULimit
      value: 120m
    - name: MemoryRequest
      value: 100Mi
    - name: MemoryLimit
      value: 400Mi
    - name: Replicas
      value: 2

  - ${{ if eq(parameters.Workload_Type, 'integration') }}:
    - name: CPURequest
      value: 40m
    - name: CPULimit
      value: 120m
    - name: MemoryRequest
      value: 100Mi
    - name: MemoryLimit
      value: 400Mi
    - name: Replicas
      value: 2
  
  - name: OpenShiftEnvironment
    value: 'tst'  
  - name: SQLExpress
    value: 'mssql-tst-transactionsdisputeportal-tst'    
  - name: ASPNETCORE_ENVIRONMENT
    value: 'Test'   
  - name: Route_Alias
    value: 'ocptst' 
  - name: Route_Direct
    value: 'ocp1'
  
  jobs:    
  - template: Deploy/Deploy_Image.yml@Templates
    parameters:
        Team: $(Team)
        Workload_Type: ${{ parameters.Workload_Type }}
        Pool: 'VSTS Release 01'
        Environment: 'OpenShift Test'
        OpenShiftEnvironment: 'tst'
        ASPNETCORE_ENVIRONMENT: 'Test'
        AppNamespace: $(AppNamespace) 
        ApplicationName: $(ApplicationName)
        Group: $(Group)
        SQLExpress: $(SQLExpress)
        ImageName: $(ImageName)
        VaultName: $(lib-VaultName)
        VaultSecret: $(lib-TstVaultSecret)
        Labels: $(Labels)
        Replicas: $(Replicas)
        CPULimit: $(CPULimit)
        CPURequest: $(CPURequest)
        MemoryRequest: $(MemoryRequest)
        MemoryLimit: $(MemoryLimit)
        Route_Alias: $(Route_Alias)
        Route_Direct: $(Route_Direct)

#=========================================================================
# DEPLOY PRODUCTION STAGE
#=========================================================================

- stage: Deploy_Production
  displayName: Deploy Production 
  trigger: manual

#=========================================================================
# VARIABLES 
#=========================================================================    

  variables:

  - ${{ if eq(parameters.Workload_Type, 'api') }}:
    - name: CPURequest
      value: 200m
    - name: CPULimit
      value: 400m
    - name: MemoryRequest
      value: 100Mi
    - name: MemoryLimit
      value: 400Mi
    - name: Replicas
      value: 2
  
  - ${{ if eq(parameters.Workload_Type, 'scheduler') }}:
    - name: CPURequest
      value: 200m
    - name: CPULimit
      value: 400m
    - name: MemoryRequest
      value: 100Mi
    - name: MemoryLimit
      value: 400Mi
    - name: Replicas
      value: 2

  - ${{ if eq(parameters.Workload_Type, 'integration') }}:
    - name: CPURequest
      value: 200m
    - name: CPULimit
      value: 400m
    - name: MemoryRequest
      value: 100Mi
    - name: MemoryLimit
      value: 400Mi
    - name: Replicas
      value: 2     

  - name: OpenShiftEnvironment
    value: 'prd'  
  - name: SQLExpress
    value: 'mssql-prd-transactionsdisputeportal-prd'    
  - name: ASPNETCORE_ENVIRONMENT
    value: 'Production'   
  - name: Route_Alias
    value: 'ocpprd' 
  - name: Route_Direct
    value: 'ocp3'
    
  jobs:
#=========================================================================
# Job Template Copy Images 
#=========================================================================
      - template: Copy/Copy_Image.yml@Templates
        parameters:
            OpenShiftEnvironment: $(OpenShiftEnvironment)  
            AppNamespace: $(AppNamespace) 
            ImageName: $(ImageName)-${{ parameters.Workload_Type }}

#=========================================================================
# Job Template Deploy Production 
#=========================================================================        
        
      - template: Deploy/Deploy_Image.yml@Templates
        parameters:
            Team: $(Team)
            Workload_Type: ${{ parameters.Workload_Type }}
            Pool: 'OSProd Release 01'
            Environment: 'OpenShift Production'
            OpenShiftEnvironment: $(OpenShiftEnvironment)  
            ASPNETCORE_ENVIRONMENT: $(ASPNETCORE_ENVIRONMENT)
            AppNamespace: $(AppNamespace) 
            ApplicationName: $(ApplicationName)
            Group: $(Group)
            SQLExpress: $(SQLExpress)
            ImageName: $(ImageName)
            VaultName: $(lib-VaultName)
            VaultSecret: $(lib-PrdVaultSecret)
            Labels: $(Labels)
            Replicas: $(Replicas)
            CPULimit: $(CPULimit)
            CPURequest: $(CPURequest)
            MemoryRequest: $(MemoryRequest)
            MemoryLimit: $(MemoryLimit)
            Route_Alias: $(Route_Alias)
            Route_Direct: $(Route_Direct)
            DependsOn: Copy_Image
            OpenshiftService: OpenShift-Production
            OSEnv: $(OpenShiftEnvironment)
            
#=========================================================================
# DEPLOY FAILOVER JOB
#=========================================================================
- stage: Deploy_DR_Production
  displayName: Deploy DR Production  
  dependsOn: Deploy_Production
  variables:
    
  - ${{ if eq(parameters.Workload_Type, 'api') }}:
    - name: CPURequest
      value: 200m
    - name: CPULimit
      value: 400m
    - name: MemoryRequest
      value: 100Mi
    - name: MemoryLimit
      value: 400Mi
    - name: Replicas
      value: 0
  
  - ${{ if eq(parameters.Workload_Type, 'scheduler') }}:
    - name: CPURequest
      value: 200m
    - name: CPULimit
      value: 400m
    - name: MemoryRequest
      value: 100Mi
    - name: MemoryLimit
      value: 400Mi
    - name: Replicas
      value: 0

  - ${{ if eq(parameters.Workload_Type, 'integration') }}:
    - name: CPURequest
      value: 200m
    - name: CPULimit
      value: 400m
    - name: MemoryRequest
      value: 100Mi
    - name: MemoryLimit
      value: 400Mi
    - name: Replicas
      value: 0     
        
  - name: OpenShiftEnvironment
    value: 'prd'  
  - name: SQLExpress
    value: 'mssql-prd-transactionsdisputeportal-prd'    
  - name: ASPNETCORE_ENVIRONMENT
    value: 'Production'   
  - name: Route_Alias
    value: 'ocpprd' 
  - name: Route_Direct
    value: 'ocp4'
    
  jobs:
#=========================================================================
# Job Template Deploy DR Production 
#=========================================================================
      - template: Deploy/Deploy_Image.yml@Templates
        parameters:
            Team: $(Team)
            Workload_Type: ${{ parameters.Workload_Type }}
            Pool: 'OSDR Release 01'
            Environment: 'OpenShift-DR Production'
            OpenShiftEnvironment: $(OpenShiftEnvironment)  
            ASPNETCORE_ENVIRONMENT: $(ASPNETCORE_ENVIRONMENT)
            AppNamespace: $(AppNamespace) 
            ApplicationName: $(ApplicationName)
            Group: $(Group)
            SQLExpress: $(SQLExpress)
            ImageName: $(ImageName)
            VaultName: $(lib-VaultName)
            VaultSecret: $(lib-PrdVaultSecret)
            Labels: $(Labels)
            Replicas: $(Replicas)
            CPULimit: $(CPULimit)
            CPURequest: $(CPURequest)
            MemoryRequest: $(MemoryRequest)
            MemoryLimit: $(MemoryLimit)
            Route_Alias: $(Route_Alias)
            Route_Direct: $(Route_Direct)
            OpenshiftService: OpenShift-Production-DR
            OSEnv: $(OpenShiftEnvironment)

#=========================================================================
# TAG Stage
#=========================================================================
#
# NOTE: The BuildService should have contribute permissions otherwise the
#       tagging step will fail
#=========================================================================
- stage: Tag
  dependsOn: 
  - Deploy_Production
  - Deploy_DR_Production
  
  jobs:
#=========================================================================
# Job Template Tagging
#=========================================================================
        - template: Prepare/gitversion_tag.yml@Templates
          parameters:
            Workload_Type: ${{ parameters.Workload_Type }}