name: $(Date:yy).$(Date:MM).$(Date:dd)$(Rev:rr)

trigger: none

resources:
  pipelines:
  - pipeline: main # Name of the pipeline resource.
    source: 'TransactionsDisputePortal Main CI' # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes
  
  repositories:
  - repository: Templates
    type: git
    name: da/pipelinetemplates

#=========================================================================
# VARIABLES 
#=========================================================================

variables:

  Database: 'transactionsdisputeportal'
  ArtifactsLocation: 'main\drop'
  SQLCreateDB: 'CreateDatabase.sql'
  SQLScriptPRE: 'ConfigDatabasePRE.sql'
  SQLMigration: 'Migration.sql'
  SQLScriptPOST: 'ConfigDatabasePOST.sql'
  
#=========================================================================
# DEPLOY TEST STAGE
#=========================================================================
stages:
- stage: Deploy_Database_Tst
  jobs:
    - template: Deploy/Deploy_Database_SQLServer.yml@Templates
      parameters:
        Environment: ''
        ResourceName: ''
        Tags: ''
        Database: $(Database)
        ArtifactsLocation: $(ArtifactsLocation)  
        SQLCreateDB: $(SQLCreateDB)  
        SQLScriptPRE: $(SQLScriptPRE)  
        SQLMigration: $(SQLMigration)  
        SQLScriptPOST: $(SQLScriptPOST)  
#=========================================================================
# DEPLOY PROD STAGE
#=========================================================================
- stage: Deploy_Database_Prd
  trigger: manual
  jobs:
    - template: Deploy/Deploy_Database_SQLServer.yml@Templates
      parameters:
        Environment: ''
        ResourceName: ''
        Tags: ''
        Database: $(Database)
        ArtifactsLocation: $(ArtifactsLocation)  
        SQLCreateDB: $(SQLCreateDB)  
        SQLScriptPRE: $(SQLScriptPRE)  
        SQLMigration: $(SQLMigration)  
        SQLScriptPOST: $(SQLScriptPOST)  
        Suffix: '-prd' 