name: $(Date:yy).$(Date:MM).$(Date:dd)$(Rev:rr)

trigger: none

pool:
  name: 'VSTS Release 01'

resources:
  pipelines:
  - pipeline: main # Name of the pipeline resource.
    source: 'TransactionsDisputePortal Main - CI' # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run pipeline when any run of completes

  repositories:
  - repository: Templates
    type: git
    name: da/pipelinetemplates

#=========================================================================
# VARIABLES 
#=========================================================================

variables:

- group: lib-config-transactionsdisputeportal

- name: ApplicationName
  value: 'transactionsdisputeportal' # Must be lowercase
- name: AppNamespace
  value: 'transactionsdisputeportal' # Must be lowercase
- name: Group
  value: 'TransactionsDisputePortal'
- name: Database 
  value:  'transactionsdisputeportal'
- name: SQLName 
  value:  'transactionsdisputeportal'
- name: SQLCreateDB 
  value: 'CreateDatabase.sql'
- name: SQLScriptPRE 
  value: 'ConfigDatabasePRE.sql'
- name: SQLMigration 
  value: 'Migration.sql'
- name: SQLScriptPOST 
  value: 'ConfigDatabasePOST.sql'
- name: BuildNumber
  value: $(resources.pipeline.main.runName)

#=========================================================================
# DEPLOY STAGES
#=========================================================================
stages:
#=========================================================================
# DEPLOY TEST DATABASE STAGE
#=========================================================================
- stage: Deploy_SQLExpress_Test
  displayName: Deploy SQLExpress Test  

  variables:
    
    OpenShiftEnvironment: 'tst'    
    InstanceSize: 12Gi    
    MemoryRequest: 1Gi   
    MemoryLimit: 3Gi

  jobs:
  - template: Deploy/Deploy_Database_SQLExpress.yml@Templates
    parameters:
        Team: $(Team)
        Environment: 'OpenShift Test'
        OpenShiftEnvironment: $(OpenShiftEnvironment)
        AppNamespace: $(AppNamespace) 
        ApplicationName: $(ApplicationName)
        Group: $(Group)
        BuildNumber: $(BuildNumber)
        SQLName: $(SQLName)
        Database: $(Database)
        ExpressPassword: $(lib-ExpressPassword)
        InstanceSize: $(InstanceSize)
        MemoryRequest: $(MemoryRequest)
        MemoryLimit: $(MemoryLimit)
        SQLCreateDB: $(SQLCreateDB)
        SQLScriptPRE: $(SQLScriptPRE)
        SQLMigration: $(SQLMigration)
        SQLScriptPOST: $(SQLScriptPOST)
        DependsOn:
        OpenshiftService: 'OpenShift'

#=========================================================================
# DEPLOY PRODUCTION DATABASE STAGE
#=========================================================================
- stage: Deploy_SQLExpress_Production
  displayName: Deploy SQLExpress Production  
  trigger: manual
  variables:
    
    OpenShiftEnvironment: 'prd'    
    InstanceSize: 12Gi    
    MemoryRequest: 1Gi   
    MemoryLimit: 3Gi

  jobs:
  - template: Deploy/Deploy_Database_SQLExpress.yml@Templates
    parameters:
        Team: $(Team)
        Environment: 'OpenShift Production'
        OpenShiftEnvironment: $(OpenShiftEnvironment)
        AppNamespace: $(AppNamespace) 
        ApplicationName: $(ApplicationName)
        Group: $(Group)
        BuildNumber: $(BuildNumber)
        SQLName: $(SQLName)
        Database: $(Database)
        ExpressPassword: $(lib-ExpressPassword)
        InstanceSize: $(InstanceSize)
        MemoryRequest: $(MemoryRequest)
        MemoryLimit: $(MemoryLimit)
        SQLCreateDB: $(SQLCreateDB)
        SQLScriptPRE: $(SQLScriptPRE)
        SQLMigration: $(SQLMigration)
        SQLScriptPOST: $(SQLScriptPOST)
        DependsOn:
        OpenshiftService: 'OpenShift-Production'
        
#=========================================================================
# DEPLOY FAILOVER DATABASE STAGE
#=========================================================================
- stage: Deploy_SQLExpress_DR
  displayName: Deploy SQLExpress DR  
  dependsOn: Deploy_SQLExpress_Production
  variables:
    
    OpenShiftEnvironment: 'prd'    
    InstanceSize: 12Gi    
    MemoryRequest: 1Gi   
    MemoryLimit: 3Gi

  jobs:
  - template: Deploy/Deploy_Database_SQLExpress.yml@Templates
    parameters:
        Team: $(Team)
        Environment: 'OpenShift-DR Production'
        OpenShiftEnvironment: $(OpenShiftEnvironment)
        AppNamespace: $(AppNamespace) 
        ApplicationName: $(ApplicationName)
        Group: $(Group)
        BuildNumber: $(BuildNumber)
        SQLName: $(SQLName)
        Database: $(Database)
        ExpressPassword: $(lib-ExpressPassword)
        InstanceSize: $(InstanceSize)
        MemoryRequest: $(MemoryRequest)
        MemoryLimit: $(MemoryLimit)
        SQLCreateDB: $(SQLCreateDB)
        SQLScriptPRE: $(SQLScriptPRE)
        SQLMigration: $(SQLMigration)
        SQLScriptPOST: $(SQLScriptPOST)
        DependsOn:
        OpenshiftService: 'OpenShift-Production-DR'